In [1]:
import requests
from bs4 import BeautifulSoup
from time import sleep
import pandas as pd
import os

In [5]:
df1 = pd.read_csv("data/weather_data.csv")
df1.drop('Unnamed: 0', axis=1, inplace=True)
df1

        zip_code        date   time  temperature  humidity  wind_speed
0         105120  2024-06-01  00:00           66        73           9
1         105120  2024-06-01  00:30           64        77           7
2         105120  2024-06-01  01:00           64        77           4
3         105120  2024-06-01  01:30           63        82           4
4         105120  2024-06-01  02:00           63        82           4
...          ...         ...    ...          ...       ...         ...
120520    143930  2024-06-20  22:00           57        88          13
120521    143930  2024-06-20  22:30           57        88          13
120522    143930  2024-06-20  23:00           57        88          11
120523    143930  2024-06-20  23:30           57        88          11
120524    143930  2024-06-20  23:55           57        88          13

[120525 rows x 6 columns]

In [7]:
df2 = pd.read_csv("data/region_info.csv")
df2.drop('Unnamed: 0', axis=1, inplace=True)
df2.drop('Unnamed: 0.1', axis=1, inplace=True)
df2.drop('Unnamed: 0.2', axis=1, inplace=True)
df2.drop("№", axis=1, inplace=True)
df2

,street,zip_code,latitude,longitude,region,hex_id
0,"""Москва, рабочий посёлок Заречье""",141270,56.148300,37.952924,"141270, Московская обл, г Пушкино, рп Софрино,...",8811aa4513fffff
1,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff
2,"""Москва, Подольское шоссе""",115093,55.711849,37.622868,"115093, г Москва, Даниловский р-н, ул Даниловс...",8811aa7815fffff
3,"""Москва, Севастопольский проспект, 11Е""",117447,55.686800,37.604013,"117447, г Москва, р-н Котловка, Севастопольски...",8811aa7829fffff
4,"""Москва, Кутузовский проспект, 9к1""",121248,55.748471,37.561185,"121248, г Москва, р-н Дорогомилово, Кутузовски...",8811aa7ae9fffff
...,...,...,...,...,...,...
158,"""Москва, улица Лобачевского, 44""",119415,55.669818,37.499754,"119415, г Москва, р-н Проспект Вернадского, ул...",8811aa7b47fffff
159,"""Москва, проспект Генерала Дорохова, 80""",121471,55.682950,37.416842,"121471, г Москва, Очаково-Матвеевское р-н, пр-...",8811aa4585fffff
160,"""Москва, Ельнинская улица, 24""",121552,55.740163,37.419976,"121552, г Москва, р-н Кунцево, ул Ельнинская, ...",8811aa44e3fffff
161,"""Москва, 1-й Хорошёвский проезд, 4к3""",125284,55.777636,37.548178,"125284, г Москва, Хорошевский р-н, 1-й Хорошёв...",8811aa7135fffff
162,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff

In [61]:
df_zip_code = df2.merge(df1, how="inner", on="zip_code")
df_zip_code
# df_zip_code.dropna()

,street,zip_code,latitude,longitude,region,hex_id,date,time,temperature,humidity,wind_speed
0,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,00:00,64,73,7
1,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,00:30,66,68,4
2,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,01:00,61,77,7
3,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,01:30,63,72,9
4,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,02:00,63,77,7
...,...,...,...,...,...,...,...,...,...,...,...
140129,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,21:30,59,82,13
140130,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,22:00,59,82,13
140131,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,22:30,59,82,13
140132,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,23:00,57,82,11
140133,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,23:30,57,88,13

In [105]:
df = df_zip_code.copy()

In [106]:
df['date'] = pd.to_datetime(df['date']).dt.date
df['time'] = pd.to_datetime(df['time'], format='%H:%M').dt.time
df['datetime'] = pd.to_datetime(df['date'].astype(str) + ' ' + df['time'].astype(str))
df['datetime_floor'] = df['datetime'].dt.floor('h')
df = df.drop_duplicates(subset=['hex_id', 'datetime_floor'], keep='first')
df

,street,zip_code,latitude,longitude,region,hex_id,date,time,temperature,humidity,wind_speed,datetime,datetime_floor
0,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,00:00:00,64,73,7,2024-06-01 00:00:00,2024-06-01 00:00:00
2,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,01:00:00,61,77,7,2024-06-01 01:00:00,2024-06-01 01:00:00
4,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,02:00:00,63,77,7,2024-06-01 02:00:00,2024-06-01 02:00:00
6,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,03:00:00,63,77,7,2024-06-01 03:00:00,2024-06-01 03:00:00
8,"""Москва, Витебская улица, 9""",121354,55.710689,37.411925,"121354, г Москва, Можайский р-н, ул Витебская,...",8811aa45ddfffff,2024-06-01,04:00:00,63,77,9,2024-06-01 04:00:00,2024-06-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
140124,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,19:00:00,59,82,18,2024-06-20 19:00:00,2024-06-20 19:00:00
140126,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,20:00:00,57,88,13,2024-06-20 20:00:00,2024-06-20 20:00:00
140128,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,21:00:00,59,82,13,2024-06-20 21:00:00,2024-06-20 21:00:00
140130,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,22:00:00,59,82,13,2024-06-20 22:00:00,2024-06-20 22:00:00
140132,"""Москва, улица Маршала Катукова, вл33""",123181,55.803269,37.422273,"123181, г Москва, р-н Строгино, ул Исаковского...",8811aa7363fffff,2024-06-20,23:00:00,57,82,11,2024-06-20 23:00:00,2024-06-20 23:00:00

In [107]:
full_range = pd.date_range(start=df['datetime_floor'].min(), end=df['datetime_floor'].max(), freq='h')
full_df = pd.DataFrame(full_range, columns=['datetime_floor'])
full_df

# # Заполнение пропущенных значений данными из предыдущих строк
# merged_df.fillna(method='ffill', inplace=True)
# 
# print(merged_df)

         datetime_floor
0   2024-06-01 00:00:00
1   2024-06-01 01:00:00
2   2024-06-01 02:00:00
3   2024-06-01 03:00:00
4   2024-06-01 04:00:00
..                  ...
475 2024-06-20 19:00:00
476 2024-06-20 20:00:00
477 2024-06-20 21:00:00
478 2024-06-20 22:00:00
479 2024-06-20 23:00:00

[480 rows x 1 columns]

In [113]:
# Объединение полного диапазона с оригинальным DataFrame
merged_df = pd.merge(full_df, df, on='datetime_floor', how='left')
merged_df.sort_values(by=['hex_id', 'date', 'time', 'datetime_floor'], ascending=True, inplace=True)
# merged_df['datetime_floor'] = pd.to_datetime(df['date'].astype(str) + ' ' + df['time'].astype(str))
merged_df

,datetime_floor,street,zip_code,latitude,longitude,region,hex_id,date,time,temperature,humidity,wind_speed,datetime
95,2024-06-01 00:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,00:00:00,64,73,7,2024-06-01 00:00:00
223,2024-06-01 01:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,01:00:00,61,77,7,2024-06-01 01:00:00
351,2024-06-01 02:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,02:00:00,63,77,7,2024-06-01 02:00:00
479,2024-06-01 03:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,03:00:00,63,77,7,2024-06-01 03:00:00
607,2024-06-01 04:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,04:00:00,63,77,9,2024-06-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60827,2024-06-20 19:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,19:00:00,57,88,13,2024-06-20 19:00:00
60955,2024-06-20 20:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,20:00:00,57,88,13,2024-06-20 20:00:00
61083,2024-06-20 21:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,21:00:00,57,88,11,2024-06-20 21:00:00
61211,2024-06-20 22:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,22:00:00,57,88,11,2024-06-20 22:00:00
61339,2024-06-20 23:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,23:00:00,57,88,11,2024-06-20 23:00:00

In [115]:
merged_df = merged_df.ffill()
merged_df

,datetime_floor,street,zip_code,latitude,longitude,region,hex_id,date,time,temperature,humidity,wind_speed,datetime
95,2024-06-01 00:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,00:00:00,64,73,7,2024-06-01 00:00:00
223,2024-06-01 01:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,01:00:00,61,77,7,2024-06-01 01:00:00
351,2024-06-01 02:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,02:00:00,63,77,7,2024-06-01 02:00:00
479,2024-06-01 03:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,03:00:00,63,77,7,2024-06-01 03:00:00
607,2024-06-01 04:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,04:00:00,63,77,9,2024-06-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60827,2024-06-20 19:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,19:00:00,57,88,13,2024-06-20 19:00:00
60955,2024-06-20 20:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,20:00:00,57,88,13,2024-06-20 20:00:00
61083,2024-06-20 21:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,21:00:00,57,88,11,2024-06-20 21:00:00
61211,2024-06-20 22:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,22:00:00,57,88,11,2024-06-20 22:00:00
61339,2024-06-20 23:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,23:00:00,57,88,11,2024-06-20 23:00:00

In [127]:
df = merged_df.copy()

In [129]:
df['temperature_fahrenheit'] = df['temperature']
df['temperature_celsius'] = round((df.temperature_fahrenheit - 32) / 1.8).astype(int)
df

,datetime_floor,street,zip_code,latitude,longitude,region,hex_id,date,time,temperature,humidity,wind_speed,datetime,temperature_fahrenheit,temperature_celsius
95,2024-06-01 00:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,00:00:00,64,73,7,2024-06-01 00:00:00,64,18
223,2024-06-01 01:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,01:00:00,61,77,7,2024-06-01 01:00:00,61,16
351,2024-06-01 02:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,02:00:00,63,77,7,2024-06-01 02:00:00,63,17
479,2024-06-01 03:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,03:00:00,63,77,7,2024-06-01 03:00:00,63,17
607,2024-06-01 04:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,04:00:00,63,77,9,2024-06-01 04:00:00,63,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60827,2024-06-20 19:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,19:00:00,57,88,13,2024-06-20 19:00:00,57,14
60955,2024-06-20 20:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,20:00:00,57,88,13,2024-06-20 20:00:00,57,14
61083,2024-06-20 21:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,21:00:00,57,88,11,2024-06-20 21:00:00,57,14
61211,2024-06-20 22:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,22:00:00,57,88,11,2024-06-20 22:00:00,57,14
61339,2024-06-20 23:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,23:00:00,57,88,11,2024-06-20 23:00:00,57,14

In [130]:
df['temperature'] = df['temperature_celsius']
df.drop('temperature_celsius', axis=1, inplace=True)
df.drop('temperature_fahrenheit', axis=1, inplace=True)
df

,datetime_floor,street,zip_code,latitude,longitude,region,hex_id,date,time,temperature,humidity,wind_speed,datetime
95,2024-06-01 00:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,00:00:00,18,73,7,2024-06-01 00:00:00
223,2024-06-01 01:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,01:00:00,16,77,7,2024-06-01 01:00:00
351,2024-06-01 02:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,02:00:00,17,77,7,2024-06-01 02:00:00
479,2024-06-01 03:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,03:00:00,17,77,7,2024-06-01 03:00:00
607,2024-06-01 04:00:00,"""Москва, Островная улица, 2с2""",121552,55.757861,37.450993,"121552, г Москва, Крылатское р-н, ул Островная...",8811aa4483fffff,2024-06-01,04:00:00,17,77,9,2024-06-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60827,2024-06-20 19:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,19:00:00,14,88,13,2024-06-20 19:00:00
60955,2024-06-20 20:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,20:00:00,14,88,13,2024-06-20 20:00:00
61083,2024-06-20 21:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,21:00:00,14,88,11,2024-06-20 21:00:00
61211,2024-06-20 22:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,22:00:00,14,88,11,2024-06-20 22:00:00
61339,2024-06-20 23:00:00,"""Москва, улица Раменки, 25к3""",119607,55.687975,37.494997,"119607, г Москва, р-н Раменки, ул Раменки, д 2...",8811aa7b5dfffff,2024-06-20,23:00:00,14,88,11,2024-06-20 23:00:00

In [136]:
df = df.reindex(
    columns=[
        'hex_id', 'street', 'region', 'latitude', 'longitude', 'datetime', 'temperature', 'humidity', 'wind_speed'
    ]
)
df

,hex_id,street,region,latitude,longitude,datetime,temperature,humidity,wind_speed
95,8811aa4483fffff,"""Москва, Островная улица, 2с2""","121552, г Москва, Крылатское р-н, ул Островная...",55.757861,37.450993,2024-06-01 00:00:00,18,73,7
223,8811aa4483fffff,"""Москва, Островная улица, 2с2""","121552, г Москва, Крылатское р-н, ул Островная...",55.757861,37.450993,2024-06-01 01:00:00,16,77,7
351,8811aa4483fffff,"""Москва, Островная улица, 2с2""","121552, г Москва, Крылатское р-н, ул Островная...",55.757861,37.450993,2024-06-01 02:00:00,17,77,7
479,8811aa4483fffff,"""Москва, Островная улица, 2с2""","121552, г Москва, Крылатское р-н, ул Островная...",55.757861,37.450993,2024-06-01 03:00:00,17,77,7
607,8811aa4483fffff,"""Москва, Островная улица, 2с2""","121552, г Москва, Крылатское р-н, ул Островная...",55.757861,37.450993,2024-06-01 04:00:00,17,77,9
...,...,...,...,...,...,...,...,...,...
60827,8811aa7b5dfffff,"""Москва, улица Раменки, 25к3""","119607, г Москва, р-н Раменки, ул Раменки, д 2...",55.687975,37.494997,2024-06-20 19:00:00,14,88,13
60955,8811aa7b5dfffff,"""Москва, улица Раменки, 25к3""","119607, г Москва, р-н Раменки, ул Раменки, д 2...",55.687975,37.494997,2024-06-20 20:00:00,14,88,13
61083,8811aa7b5dfffff,"""Москва, улица Раменки, 25к3""","119607, г Москва, р-н Раменки, ул Раменки, д 2...",55.687975,37.494997,2024-06-20 21:00:00,14,88,11
61211,8811aa7b5dfffff,"""Москва, улица Раменки, 25к3""","119607, г Москва, р-н Раменки, ул Раменки, д 2...",55.687975,37.494997,2024-06-20 22:00:00,14,88,11
61339,8811aa7b5dfffff,"""Москва, улица Раменки, 25к3""","119607, г Москва, р-н Раменки, ул Раменки, д 2...",55.687975,37.494997,2024-06-20 23:00:00,14,88,11